domain: domain

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${domain}:8000/eureka/

spring:
  datasource:
    name: testmywarehouse
    url: jdbc:mysql://127.0.0.1:3306/bskj?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: service-feign-activiti
  activiti:
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/


mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.bskj.system.model  # 注意：对应实体类的路径
