server:
  port: 8899
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinghaosun123/SpringCloudConfiguration.git
          search-paths: config
      label: master



#logging:
#  config: classpath:logback.xml
#  level:
#    org:
#      springframework:
#        web: info